title: "Sebastian Ritter"
description: "PhD Candidate in Economics"

# Usamos Minimal Mistakes como Remote Theme
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme

include:
  - assets/css/custom.css
